### ISSUE TITLE
Error: undefined method 'psubscribe' for Redis::Client

### ISSUE THREAD

**Issue by robacarp** [jgaskins/redis#46]
In a project with redis installed like this: (from shard.lock)

```
version: 2.0
shards:
  redis:
    git: https://github.com/jgaskins/redis.git
    version: 0.7.0
```

I'm unable to use the psubscribe method:

```crystal
require "redis"

redis = Redis::Client.new

redis.psubscribe "*" do |on|
  on.message do |channel, message|
    puts message
  end
end
```

#subscribe works fine, however. 

```
In test_for_psubscribe.cr:5:7

 5 | redis.psubscribe "channel1", "channel2" do |subscription, connection|
           ^---------
Error: undefined method 'psubscribe' for Redis::Client
```

I poked briefly at the code in lib/redis and can see that it generates the function, but it's not getting imported up into Redis::Client like #subscribe is. I didn't look hard at finding a way to get the connection from the client to call psubscribe on, because it seemed like it got forgotten.
